import mongoose from 'mongoose';

export const TIMELINE_TYPES = [
  'friendship_started', 'first_message', 'first_voice_note', 'first_photo',
  'first_call', 'milestone_messages', 'games_played', 'badge_earned',
  'anniversary', 'identity_restored', 'custom',
];

/**
 * Timeline events are EMITTED when they happen, never derived by scanning
 * history at render time. That is what keeps the Friendship Timeline a cheap
 * indexed read when there are 200,000 messages behind it.
 */
const timelineEventSchema = new mongoose.Schema({
  friendshipId: {
    type: mongoose.Schema.Types.ObjectId,
    ref: 'Friendship',
    required: true,
    index: true,
  },
  type: { type: String, enum: TIMELINE_TYPES, required: true },
  occurredAt: { type: Date, default: Date.now },
  actorId: { type: mongoose.Schema.Types.ObjectId, ref: 'User', default: null },

  title: { type: String, default: '' },
  description: { type: String, default: '' },
  icon: { type: String, default: '✨' },
  meta: { type: mongoose.Schema.Types.Mixed, default: {} },

  autoGenerated: { type: Boolean, default: true },
  // "First message" can only ever happen once per friendship. This key makes
  // that structurally true instead of relying on the emitter checking first.
  uniqueKey: { type: String, default: null },
}, { timestamps: true });

timelineEventSchema.index({ friendshipId: 1, occurredAt: -1 });
timelineEventSchema.index(
  { friendshipId: 1, uniqueKey: 1 },
  { unique: true, partialFilterExpression: { uniqueKey: { $type: 'string' } } },
);

export const TimelineEvent = mongoose.model('TimelineEvent', timelineEventSchema);
